### ISSUE TITLE
Fatal error: Cannot assign to read only property 'subarray'

### ISSUE THREAD

**Issue by chrischain** [mathiasbynens/grunt-yui-compressor#28]
I recently started seeing the following error:

`Fatal error: Cannot assign to read only property 'subarray' of {entire contents of my file to be concat/minified}`

I have not made any changes to my gruntfile, however I did update all of my packages to the latest versions, including grunt-yui-compressor.

It appears to still perform the concat/min functions and move the file to our disk share, but the errors are a bit annoying.

**Comment by Kylir** [comment]
I saw this error as well. It appears after I installed NodeJS 0.12.

**Comment by kyleva** [comment]
@Kylir +1 -- worked for me, thanks!
